// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lmsdhasanlytnjkccgqn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxtc2RoYXNhbmx5dG5qa2NjZ3FuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxNzU3NjAsImV4cCI6MjA2Mzc1MTc2MH0.DTdkCbi1Xw0re_eN1AmPgQT81a2PmK1On0dAAnUK86Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);